### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Test
GET http://localhost:8080/api/users


### JWT AUTH
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###